### ISSUE TITLE
Make Error 2

### ISSUE THREAD

**Issue by Nonikka** [rpicopter/MotionSensorExample#4]
Hello ,this is my problem:

root@navio-rpi:/home/pi/MotionSensorExample-master# make
make -C MotionSensor/
make[1]: Entering directory '/home/pi/MotionSensorExample-master/MotionSensor'
g++ -Wall -g -O2 -c -DMPU6050 -DMPU_DEBUGOFF -I../libs/ inv_mpu_lib/inv_mpu.c -o inv_mpu_lib/inv_mpu.o
inv_mpu_lib/inv_mpu.c:392:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:393:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:394:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:395:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:396:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:397:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:398:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:399:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:400:3: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:401:3: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:402:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:403:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:404:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:405:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:406:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:407:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:408:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:409:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:410:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:411:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:412:3: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:413:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:414:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:415:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:416:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:417:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:418:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:419:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:420:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:421:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:439:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:440:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:441:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:442:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:443:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:444:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:452:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:453:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:454:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:455:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:456:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:457:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:458:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:459:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:460:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:461:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:462:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:463:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:464:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:465:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:470:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:471:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c:472:2: error: expected primary-expression before ‘.’ token
inv_mpu_lib/inv_mpu.c: In function ‘uint8_t mpu_lp_motion_interrupt(uint16_t, uint8_t, uint8_t)’:
inv_mpu_lib/inv_mpu.c:2809:45: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
inv_mpu_lib/inv_mpu.c: At global scope:
inv_mpu_lib/inv_mpu.c:2408:12: warning: ‘int setup_compass()’ defined but not used [-Wunused-function]
Makefile:12: recipe for target 'inv_mpu_lib/inv_mpu.o' failed
make[1]: **\* [inv_mpu_lib/inv_mpu.o] Error 1
make[1]: Leaving directory '/home/pi/MotionSensorExample-master/MotionSensor'
Makefile:22: recipe for target 'MotionSensor/libMotionSensor.a' failed
make: **\* [MotionSensor/libMotionSensor.a] Error 2

I just "make" in my Pi,but ...
Can you give me some advice?Thank you

**Comment by gregd72002** [comment]
It is likely to do with the version of compiler you are using

**Comment by JeanCollas** [comment]
I am facing the same issue on a Raspberry Pi 2B/Raspbian. How could I use a compatible version?
I have read the other post concerning the same issue, but as I am not very familiar with compilers issues, I would be happy to understand better the issue, and how to solve it without changing the code (C99 syntax should be supported). 

Thanks

**Comment by gregd72002** [comment]
The explanation of the issue is here: http://stackoverflow.com/questions/5790534/static-structure-initialization-with-tags-in-c

You might want to change the compiler in Makefile, line 1: CXX=gcc

Alternatively convert the structure initialisation into function. Call the function, i.e. from mpu_init.

**Comment by Nonikka** [comment]
I tried another https://github.com/richardghirst/PiBits/tree/master/MPU6050-Pi-Demo
It works,but thank you all the same!
I will try this  next time

**Comment by JeanCollas** [comment]
I have actually found this one as well, it works great after addresses adjustments.
I have also found https://github.com/wennycooper/mpu6050_in_c which works quite well. I don't know yet on which I am going to work.

**Comment by Nonikka** [comment]
I think I should close this issue,if have other problem,we can talk in private.Thanks for comment.
